# Copyright (c) 2020-now by the Zeek Project. See LICENSE for details.

path_classifiers:
  library:
    - "3rdparty"

extraction:
  cpp:
    prepare:
      packages:
        - git
        - ninja-build
        - bison
        - flex
        - bison
        - llvm-12-dev
        - clang-12
        - libclang-12-dev
        - libc++1
        - libc++abi1
        - libc++abi-dev
        - curl
    after_prepare:
        - mkdir $HOME/cmake && curl -L https://github.com/Kitware/CMake/releases/download/v3.19.2/cmake-3.19.2-Linux-x86_64.tar.gz | tar xzvf - -C $HOME/cmake --strip-components 1
        - export PATH=$HOME/cmake/bin:$PATH
        - export CXX=clang++-12
        - export CC=clang-12
        - export ASM=clang-12
        - git fetch --tags

    configure:
      command:
        - cmake --version
        - ./configure --generator=Ninja --enable-debug

    index:
      build_command:
        - ninja -C build
