# Copyright (c) 2020-2023 by the Zeek Project. See LICENSE for details.

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  fail_on_warning: false
  configuration: doc/conf.py

python:
  version: "3"
  system_packages: false
  install:
    - requirements: doc/requirements.txt
