name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Get version
      run: echo "::set-output name=RELEASE_VERSION::$(./scripts/autogen-version --short)"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ci/Dockerfile
        push: true
        tags: |
          bbannier/spicy:latest
          bbannier/spicy:${{ steps.get_version.outputs.RELEASE_VERSION }}
