name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Get version
      run: echo ::save-state name=RELEASE_VERSION::$(./scripts/autogen-version --short)
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: bbannier/spicy
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/Dockerfile.ubuntu-18
        tags: "latest,${{ env.STATE_RELEASE_VERSION }}"
